import { _electron as electron } from 'playwright';
import electronPath from 'electron';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';

const root=process.cwd(),version=JSON.parse(await fs.readFile('package.json','utf8')).version;
const tag=new Date().toISOString().replace(/[:.]/g,'-');
const data=path.join(root,'.runtime','library-smoke',tag);
const out=path.join(root,'output','playwright',`library-${version}${process.env.MK_PACKAGED_EXE?'-packaged':''}`);
await fs.mkdir(out,{recursive:true});await fs.mkdir(path.join(data,'fixtures'),{recursive:true});await fs.mkdir(path.join(data,'test-trash'),{recursive:true});
const env={...process.env,MK_FIGURE_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;
const launch=()=>electron.launch({executablePath:process.env.MK_PACKAGED_EXE||electronPath,args:process.env.MK_PACKAGED_EXE?[]:[root],env,timeout:60000});
let client=await launch();const errors=[];const views=[];
const prepare=async()=>{
 const page=await client.firstWindow();page.on('pageerror',error=>errors.push(error.message));
 await client.evaluate(({BrowserWindow})=>{const win=BrowserWindow.getAllWindows()[0];win.webContents.setBackgroundThrottling(false);win.setContentSize(1440,900);win.show();win.focus();});
 await page.getByRole('button',{name:/^新建科研图/}).waitFor({timeout:60000});return page;
};
const capture=async(page,name)=>{
 await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:path.join(out,`${name}.png`)});
 const size=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,panels:[...document.querySelectorAll('.library-page,.library-toolbar,.library-detail,.reference-selection')].map(e=>({class:e.className,width:e.clientWidth,scrollWidth:e.scrollWidth}))}));
 assert.ok(size.scrollWidth<=size.width+1,`${name} page overflow`);
 assert.ok(size.panels.every(p=>p.scrollWidth<=p.width+1),`${name} panel overflow`);views.push({name,...size});
};
const dialogFiles=files=>client.evaluate(({dialog},filePaths)=>{dialog.showOpenDialog=async()=>({canceled:!filePaths.length,filePaths});},files);
const card=(page,id)=>page.locator(`[data-library-id="${id}"]`);
try {
 let page=await prepare();
 assert.equal(await page.locator('.start-routes > button').count(),3);
 assert.equal(await page.getByRole('button',{name:/^离线示例/}).count(),0);
 await capture(page,'01-home');
 const builtins=await page.evaluate(()=>window.mkFigure.listLibrary());
 assert.equal(builtins.length,13);assert.equal(builtins.filter(i=>i.category==='icon'&&i.extension==='svg').length,10);
 for(const item of builtins.filter(item=>item.category==='reference'))assert.ok((await page.evaluate(id=>window.mkFigure.getLibraryPreview(id),item.id)).startsWith('data:image/png;base64,'));
 await page.getByRole('button',{name:/^图片素材库/}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.library-card').length===13);
 await capture(page,'02-library');
 await page.locator('.library-filters button').filter({hasText:'图标'}).click();
 assert.equal(await page.locator('.library-card').count(),10);await capture(page,'03-icons');
 await page.getByRole('button',{name:'预览 通信基站',exact:true}).click();
 await page.getByRole('dialog').waitFor();
 const preview=await page.locator('.library-detail-image img').evaluate(i=>({w:i.naturalWidth,h:i.naturalHeight}));
 assert.equal(Math.max(preview.w,preview.h),1024);await capture(page,'04-icon-detail');
 await page.getByRole('button',{name:'关闭素材预览'}).click();
 for(const action of ['updateLibraryItem','deleteLibraryItem'])await assert.rejects(()=>page.evaluate(({action})=>window.mkFigure[action]('pastel-method',{name:'forbidden'}),{action}));

 const svg='<svg xmlns="http://www.w3.org/2000/svg" width="160" height="100" viewBox="0 0 160 100"><rect x="8" y="8" width="144" height="84" rx="18" fill="#E6EEE6"/><path d="M35 65L65 35L93 66L128 31" fill="none" stroke="#43745B" stroke-width="7"/><circle cx="65" cy="35" r="8" fill="#B67652"/></svg>';
 const svgFile=path.join(data,'fixtures','Personal vector.svg');await fs.writeFile(svgFile,svg);
 const rasters=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=100;const x=c.getContext('2d');x.fillStyle='#a96c4e';x.fillRect(0,0,160,100);x.fillStyle='#f7f5f0';x.fillRect(24,24,112,52);return ['png','jpeg','webp'].map(ext=>({ext,url:c.toDataURL('image/'+ext)}));});
 const rasterFiles=[];for(const raster of rasters){assert.ok(raster.url.startsWith(`data:image/${raster.ext};`));const file=path.join(data,'fixtures',`Personal raster.${raster.ext}`);await fs.writeFile(file,Buffer.from(raster.url.split(',')[1],'base64'));rasterFiles.push(file);}
 const bad=path.join(data,'fixtures','Unsafe.svg');await fs.writeFile(bad,'<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"><script>alert(1)</script></svg>');
 await dialogFiles([svgFile,...rasterFiles,bad]);
 await page.getByRole('combobox',{name:'导入素材分类',exact:true}).selectOption('icon');
 await page.getByRole('button',{name:'导入图片',exact:true}).click();
 await page.getByText('已导入 4 张素材',{exact:true}).waitFor({timeout:60000});
 await page.getByText('1 个文件未导入',{exact:true}).waitFor();
 const imported=await page.evaluate(()=>window.mkFigure.listLibrary());assert.equal(imported.length,17);
 const own=imported.find(i=>i.name==='Personal vector');assert.ok(own);
 await card(page,own.id).getByRole('button',{name:'预览 Personal vector',exact:true}).click();
 await page.getByRole('textbox',{name:'素材名称',exact:true}).fill('我的方法框架');
 await page.getByRole('combobox',{name:'素材类别',exact:true}).selectOption('reference');
 await page.getByRole('button',{name:'保存更改',exact:true}).click();
 await page.getByRole('button',{name:'保存更改',exact:true}).waitFor({state:'visible'});
 await page.waitForFunction(()=>document.querySelector('.library-detail-panel input')?.value==='我的方法框架'&&document.querySelector('.library-detail-actions button')?.disabled===false);
 const exported=path.join(out,'original-vector.svg');
 await client.evaluate(({dialog},filePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath});},exported);
 await page.getByRole('button',{name:'导出原文件',exact:true}).click();
 await page.locator('.library-detail-notice').filter({hasText:'原文件已导出'}).waitFor();
 assert.equal(await fs.readFile(exported,'utf8'),svg);
 // A selected external directory must not bypass protection via an NTFS junction.
 const junction=path.join(data,'fixtures','library-alias');
 await fs.symlink(path.join(data,'library',own.id),junction,process.platform==='win32'?'junction':'dir');
 await client.evaluate(({dialog},filePath)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath});},path.join(junction,'original.svg'));
 await assert.rejects(()=>page.evaluate(id=>window.mkFigure.exportLibraryItem(id),own.id),/软件数据目录/);
 assert.equal(await fs.readFile(path.join(data,'library',own.id,'original.svg'),'utf8'),svg);
 await fs.unlink(junction);
 await capture(page,'05-personal-material');
 await page.getByRole('button',{name:'关闭素材预览'}).click();
 await page.locator('.library-back').click();await page.getByRole('button',{name:/^新建科研图/}).click();
 await page.getByPlaceholder('粘贴一段内容',{exact:false}).fill('神经 ODE：输入、积分求解与参数更新');
 await page.getByPlaceholder('例如：简洁学术风格',{exact:false}).fill('蓝绿配色，保留英文缩写');
 await page.getByRole('button',{name:'从素材库选择',exact:true}).click();
 await card(page,own.id).getByRole('button',{name:'用作风格',exact:true}).click();
 await page.getByText('主题与重点',{exact:true}).waitFor();
 assert.equal(await page.getByPlaceholder('粘贴一段内容',{exact:false}).inputValue(),'神经 ODE：输入、积分求解与参数更新');
 assert.equal(await page.locator('.reference-grid,.reference-card,.active-reference').count(),0);
 let current=await page.evaluate(async()=>{const b=await window.mkFigure.bootstrap();return window.mkFigure.openProject(b.projects[0].id);});
 assert.equal(current.stage,'brief');assert.equal(current.libraryReferenceId,own.id);assert.equal(current.customReference.name,'我的方法框架.png');
 assert.equal(current.brief.stylePrompt,'蓝绿配色，保留英文缩写');
 await capture(page,'06-brief-compact-reference');
 await page.getByRole('button',{name:/生成视觉稿/}).first().click();
 await page.getByRole('button',{name:'从素材库选择',exact:true}).click();
 await card(page,'pastel-method').getByRole('button',{name:'用作风格',exact:true}).click();
 await page.locator('textarea.prompt-area').waitFor();
 current=await page.evaluate(id=>window.mkFigure.openProject(id),current.id);assert.equal(current.stage,'visual');assert.equal(current.libraryReferenceId,'pastel-method');
 await page.getByRole('button',{name:'从素材库选择',exact:true}).click();
 await card(page,own.id).getByRole('button',{name:'用作风格',exact:true}).click();
 await page.locator('textarea.prompt-area').waitFor();
 current=await page.evaluate(id=>window.mkFigure.openProject(id),current.id);
 const snapshot=await fs.readFile(path.join(data,'projects',current.id,'assets',current.customReference.path));
 await page.getByRole('button',{name:'从素材库选择',exact:true}).click();
 await card(page,own.id).getByRole('button',{name:'预览 我的方法框架',exact:true}).click();
 await client.evaluate(({dialog,shell},settings)=>{
  const io=process.getBuiltinModule('node:fs/promises'),p=process.getBuiltinModule('node:path');
  globalThis.__libraryDelete={response:0,called:0};
  dialog.showMessageBox=async(_window,options)=>{globalThis.__libraryDelete.options=options;return {response:globalThis.__libraryDelete.response};};
  shell.trashItem=async directory=>{if(directory!==settings.target)throw new Error('Unexpected test trash target');globalThis.__libraryDelete.called++;await io.rename(directory,p.join(settings.trash,p.basename(directory)));};
 },{target:await fs.realpath(path.join(data,'library',own.id)),trash:await fs.realpath(path.join(data,'test-trash'))});
 await page.getByRole('button',{name:'删除素材',exact:true}).click();
 await page.waitForFunction(()=>!document.querySelector('.library-delete')?.disabled);
 assert.equal((await client.evaluate(()=>globalThis.__libraryDelete)).called,0);
 await client.evaluate(()=>{globalThis.__libraryDelete.response=1;});
 await page.getByRole('button',{name:'删除素材',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 assert.equal((await client.evaluate(()=>globalThis.__libraryDelete)).options.defaultId,0);
 assert.equal(await card(page,own.id).count(),0);
 await page.locator('.library-back').click();await page.locator('textarea.prompt-area').waitFor();
 const afterDelete=await page.evaluate(id=>window.mkFigure.openProject(id),current.id);
 assert.equal(afterDelete.libraryReferenceId,own.id);assert.ok(afterDelete.customReference.previewUrl.startsWith('data:image/png;'));
 assert.deepEqual(await fs.readFile(path.join(data,'projects',current.id,'assets',afterDelete.customReference.path)),snapshot);
 await dialogFiles([]);const cancelled=await page.evaluate(()=>window.mkFigure.importLibraryFiles('icon'));assert.deepEqual(cancelled.importedIds,[]);assert.equal(cancelled.items.length,16);
 await page.getByRole('button',{name:'清除风格参考'}).click();await page.getByRole('button',{name:'从素材库选择'}).click();await page.locator('.library-back').click();
 const cleared=await page.evaluate(id=>window.mkFigure.openProject(id),current.id);assert.equal(cleared.customReference,undefined);assert.equal(cleared.libraryReferenceId,undefined);
 await client.close();client=await launch();page=await prepare();
 const reopened=await page.evaluate(()=>window.mkFigure.listLibrary());assert.equal(reopened.length,16);assert.equal(reopened.filter(i=>i.source==='user').length,3);
 await page.getByRole('button',{name:/^图片素材库/}).click();await page.waitForFunction(()=>document.querySelectorAll('.library-card').length===16);
 await client.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(960,640));await capture(page,'07-library-minimum');
 await page.getByRole('textbox',{name:'搜索素材',exact:true}).fill('通信');assert.equal(await page.locator('.library-card').count(),1);
 await page.getByRole('button',{name:'预览 通信基站',exact:true}).click();await page.getByRole('dialog').waitFor();await capture(page,'08-detail-minimum');
 assert.deepEqual(errors,[]);
 const report={passed:true,version,builtins:13,svgIcons:10,importedFormats:['SVG','PNG','JPEG','WebP'],invalidSvgRejected:true,renameCategoryPersisted:true,originalSvgUnchanged:true,briefEditsPreserved:true,originalStageRestored:true,projectReferenceSurvivesDeletion:true,cancelPreservesMaterial:true,clearReference:true,personalLibrarySurvivesRestart:true,views,pageErrors:errors,simulatedSystemDialogsAndTrash:true,liveModelsCalled:false};
 await fs.writeFile(path.join(out,'results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
} catch(error){const page=(await client.windows())[0];if(page)await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});throw error;}
finally{await client.close();}
